"use client";

import { useQuery } from "@tanstack/react-query";
import { FileText, Users } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { orpc } from "@/lib/orpc";

export const DashboardStats = () => {
  const { data, isLoading, error } = useQuery(orpc.getStats.queryOptions());

  if (isLoading) {
    return (
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        {[...Array(2)].map((_) => (
          <Card key={crypto.randomUUID()}>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <Skeleton className="h-4 w-[100px]" />
            </CardHeader>
            <CardContent>
              <Skeleton className="h-8 w-[60px] mb-1" />
              <Skeleton className="h-3 w-[120px]" />
            </CardContent>
          </Card>
        ))}
      </div>
    );
  }

  if (error) {
    return (
      <div className="text-destructive p-4">Failed to load statistics.</div>
    );
  }

  return (
    <div className="grid gap-4 md:grid-cols-2">
      <Card className="relative overflow-hidden">
        <div className="absolute right-0 top-0 h-24 w-24 translate-x-8 translate-y--8 rounded-full bg-primary/10" />
        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
          <CardTitle className="text-sm font-medium">
            Total Certificates
          </CardTitle>
          <div className="rounded-full bg-primary/10 p-2">
            <FileText className="h-4 w-4 text-primary" />
          </div>
        </CardHeader>
        <CardContent>
          <div className="text-3xl font-bold">{data?.total ?? 0}</div>
          <p className="text-xs text-muted-foreground mt-1">
            Generated by all users
          </p>
        </CardContent>
      </Card>
      <Card className="relative overflow-hidden">
        <div className="absolute right-0 top-0 h-24 w-24 translate-x-8 translate-y--8 rounded-full bg-chart-2/10" />
        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
          <CardTitle className="text-sm font-medium">My Certificates</CardTitle>
          <div className="rounded-full bg-chart-2/10 p-2">
            <Users className="h-4 w-4 text-chart-2" />
          </div>
        </CardHeader>
        <CardContent>
          <div className="text-3xl font-bold">{data?.userTotal ?? 0}</div>
          <p className="text-xs text-muted-foreground mt-1">Generated by you</p>
        </CardContent>
      </Card>
    </div>
  );
};
